[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.2.4", features = ["web"] }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
js-sys = "0.3"
log = "0.4.6"
wasm-logger = "0.2.0"
petgraph = "0.6.0"
serde = {version = "*", features = ["derive"]}
serde_cbor = "0.11.1"
bincode = "1.3.3"
rkyv = { version = "0.7", features = ["validation"] }

[dependencies.web-sys]
version = "0.3.22"
features = [
  "BinaryType",
  "Blob",
  "ErrorEvent",
  "FileReader",
  "MessageEvent",
  "ProgressEvent",
  "WebSocket",
]
