[package]
name = "client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.2", features = ["web", "fermi"] }
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
js-sys = "0.3"
log = "0.4.6"
wasm-logger = "0.2.0"
petgraph = "0.6.0"
serde = {version = "*", features = ["derive"]}
serde_cbor = "0.11.1"
bincode = "1.3.3"
bytecheck = "0.6.8"
gen-planet-name = { path = "../gen-planet-name" }
beyond-core = { path = "../core" }
sycamore = { version = "0.8.0-beta.5", features = ["serde", "suspense"] }
gloo = "0.7.0"
futures = "0.3.21"
yew = "0.19.3"
wasm-bindgen-futures = "0.4.30"
yew-router = "0.16.0"
yew-agent = "0.1.0"
stylist = { version = "0.10", features = ["yew"] }
uuid = { version = "0.8", features = ["v4", "wasm-bindgen"] }

[dependencies.web-sys]
version = "0.3.22"
features = [
  "BinaryType",
  "Blob",
  "ErrorEvent",
  "FileReader",
  "MessageEvent",
  "ProgressEvent",
  "WebSocket",
]
