version: '3'

includes:
  ui: ./libs/ui

tasks:
  start:
    desc: start client
    cmds:
      - pnpm start beyond

  lint:
    desc: lint
    cmds:
      - pnpm lint:all

  lint:fix:
    desc: lint
    cmds:
      - pnpm lint:all --fix
