version: '3'

includes:
  server:
    taskfile: ./packages/server/Taskfile.yml
    dir: ./packages/server
  client:
    taskfile: ./packages/client/Taskfile.yml
    dir: ./packages/client

tasks:
  init:
    desc: initialize projects
    cmds:
      - cargo install cargo-watch cargo-generate wasm-bindgen-cli wasm-pack trunk
      - rustup target add wasm32-unknown-unknown
      - npm install -g tailwindcss

  start:
    desc: start all applications
    deps:
      - task: mongo:start
      - task: client:start
      - task: server:start

  mongo:start:
    desc: start mongodb
    cmds:
      - docker-compose up -d && docker-compose logs -f mongo

  check:
    desc: check applications
    cmds:
      - task: server:check

  test:
    desc: test applications
    cmds:
      - task: server:test

  lint:
    desc: lint applications
    cmds:
      - task: server:lint
      - task: client:lint

  lint:fix:
    desc: lint applications and fix them if possible
    cmds:
      - task: server:lint:fix
      - task: client:lint:fix

  format:
    desc: format
    cmds:
      - task: server:format

  fix:all:
    desc: fix all
    cmds:
      - task: lint:fix
      - task: format
      - task: check
