version: '3'

includes:
  server:
    taskfile: ./packages/server/Taskfile.yml
    dir: ./packages/server
  client:
    taskfile: ./packages/client/Taskfile.yml
    dir: ./packages/client
  core:
    taskfile: ./packages/core/Taskfile.yml
    dir: ./packages/core
  gen-planet-name:
    taskfile: ./packages/gen-planet-name/Taskfile.yml
    dir: ./packages/gen-planet-name

tasks:
  init:
    desc: initialize projects
    cmds:
      - cargo install cargo-watch cargo-generate wasm-bindgen-cli wasm-pack trunk
      - rustup target add wasm32-unknown-unknown
      - npm install -g tailwindcss

  start:
    desc: start all applications
    deps:
      - task: mongo:start
      - task: client:start
      - task: server:start

  mongo:start:
    desc: start mongodb
    cmds:
      - docker-compose up -d && docker-compose logs -f mongo

  check:
    desc: check applications
    cmds:
      - cargo check --all

  test:
    desc: test applications
    cmds:
      - task: server:shared:test
      - task: core:shared:test
      - task: gen-planet-name:shared:test

  lint:
    desc: lint applications
    cmds:
      - cargo clippy --all

  lint:fix:
    desc: lint applications and fix them if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format applications
    cmds:
      - cargo +nightly fmt --all

  fix:all:
    desc: fix all
    cmds:
      - task: lint:fix
      - task: format
      - task: check
