[package]
name = "beyond-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
serde = { version = "1.0", features = ["derive"] }
getrandom = { version = "0.2", features = ["js"] }
bincode = "1.3.3"
gen-planet-name = { path = "../gen-planet-name" }
serde_json = "1.0.81"
bson = { version = "2.0.0", features = ["chrono-0_4", "uuid-0_8", "serde_with"] }
actix = "0.13.0"
actix-web = "4"
argon2 = "0.3"
rand_core = { version = "0.6", features = ["std"] }
