[package]
name = "wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2.80", features = ["serde-serialize"] }
log = "0.4.6"
wasm-logger = "0.2.0"
beyond-core = { path = "../core" }
bincode = "1.3.3"
serde = { version = "1.0", features = ["derive"] }
js-sys = "0.3.57"
