[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4"
actix-web-actors = "4"
log = "0.4"
fast_log="1.3"
mongodb = "2.2.1"
dotenvy = "0.15.1"
futures-util = "0.3.21"
beyond-core = { path = "./core" }
futures = "0.3"
rust_socketio = "0.3.1"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
jsonwebtoken = "8"
chrono = "0.4.19"
