[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4"
actix-web-actors = "4"
log = "0.4"
fast_log="1.3"
mongodb = { version = "2.2.1", features = ["bson-uuid-0_8", "bson-chrono-0_4"] }
dotenvy = "0.15.1"
futures-util = "0.3.21"
beyond-core = { path = "../core" }
futures = "0.3"
