version: '3'

includes:
  shared:
    taskfile: ../../SharedTaskfile.yml
    dir: ./

tasks:
  start:
    desc: start server
    cmds:
      - cargo-watch -x run

  check:
    desc: check applications
    cmds:
      - cargo check --all

  test:
    desc: test applications
    cmds:
      - cargo test --all

  lint:
    desc: lint applications
    cmds:
      - cargo clippy --all

  lint:fix:
    desc: lint server and fix if possible
    cmds:
      - cargo clippy --fix --allow-dirty --all

  format:
    desc: format
    cmds:
      - cargo +nightly fmt --all
